#!/usr/bin/env bash
#A bash script that displays numbers from 1 to 100 and
#+Displays FizzBuzz when the number is a multiple of 3 and 5
#+Displays Fizz when the number is multiple of 3
#+Displays Buzz when the number is a multiple of 5
#+Otherwise, displays the number
#In a list format

for ((n = 1; n < 101; n++))
do
	if [ $((n % 3)) -eq 0 ] && [ $((n % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((n % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((n % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$n"
	fi
done
