#!/usr/bin/env bash
#A bash script that displays the content of the file /etc/passwd
#The script displays only the
#+username
#+user id
#+Home directory path for the user

while read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < /etc/passwd
