#!/usr/bin/env bash
#A script that uses a while loop to write "Best School"v10 times and also using "if".

i=0
while [ $i -lt 10 ]
do
	echo "Best School"

	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi

	i=$((i + 1))
done

