#!/usr/bin/env bash
#A bash script that displays:

#+The content of the current directory
#+In a list format
#+Where only the part of the name after the first dash is displayed

list=$(ls)
for m in $list
do
	echo "$m" | cut -d '-' -f2
done
